services:
  ghost:
    image: kioshiokamoto/ghost:theme-3
    restart: always
    ports:
      - "2368:2368"
    environment:
      # mas config en https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost

      #Enlace de ghost
      url: http://20.88.211.156:2368

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
